import type { Clip } from "@openreel/core";

import { useProjectStore } from "../stores/project-store";
import { listComponentMetadata, putComponentMetadata } from "./server-storage";

/**
 * Bookkeeping for clips generated by the Component Library panel.
 *
 * The panel imports a rendered file into the media library, but the *clip* only exists
 * once the user drops that media on a track — so the component's identity is recorded
 * here against the media id, and stamped onto `clip.metadata` as soon as a clip appears.
 *
 * `Clip.metadata` is typed `ClipMetadata` with an open index signature
 * (`packages/core/src/types/timeline.ts:82`), so this needs no core schema change and
 * survives OpenReel's JSON export/import untouched.
 */

export const COMPONENT_LIBRARY_SOURCE = "component-library";

export interface ComponentClipMetadata {
  source: typeof COMPONENT_LIBRARY_SOURCE;
  componentId: string;
  props: Record<string, unknown>;
  /** The render-service file this clip's media came from, e.g. "7.webm". */
  renderedFileId: string;
  /** Chroma backdrop the file was rendered on, so a re-render reproduces it exactly. */
  background: string | null;
}

type PendingRegistry = Record<string, Omit<ComponentClipMetadata, "source">>;

/**
 * mediaId -> component info for media generated but not yet placed on a track.
 *
 * Stage 8: this was a localStorage registry (Stage 5's deferred item #3). The server-side
 * `component_metadata` table is now the source of truth; this map is only an in-memory
 * cache of what the server returned, hydrated by `refreshRegistry()`.
 */
let registry: PendingRegistry = {};

function readPending(): PendingRegistry {
  return registry;
}

/** Pulls the server's component metadata into the cache, then stamps any waiting clips. */
export async function refreshRegistry(): Promise<number> {
  try {
    const entries = await listComponentMetadata();
    const next: PendingRegistry = {};
    for (const entry of entries) {
      next[entry.mediaId] = {
        componentId: entry.componentId,
        props: entry.props,
        renderedFileId: entry.renderedFileId ?? "",
        background: entry.background,
      };
    }
    registry = next;
    stampClips();
    return entries.length;
  } catch (error) {
    console.warn("[component-library] could not load server metadata:", error);
    return 0;
  }
}

export function registerGeneratedMedia(
  mediaId: string,
  info: Omit<ComponentClipMetadata, "source">,
): void {
  registry[mediaId] = info;
  stampClips();

  // Persist server-side so the mapping survives on a completely different browser.
  void putComponentMetadata({
    mediaId,
    componentId: info.componentId,
    props: info.props,
    background: info.background,
    renderedFileId: info.renderedFileId,
  }).catch((error) => {
    console.warn("[component-library] could not save server metadata:", error);
  });
}

export function getComponentMetadata(clip: Clip | undefined): ComponentClipMetadata | null {
  const metadata = clip?.metadata as Partial<ComponentClipMetadata> | undefined;
  if (!metadata || metadata.source !== COMPONENT_LIBRARY_SOURCE) return null;
  if (!metadata.componentId) return null;
  return {
    source: COMPONENT_LIBRARY_SOURCE,
    componentId: metadata.componentId,
    props: (metadata.props ?? {}) as Record<string, unknown>,
    renderedFileId: metadata.renderedFileId ?? "",
    background: metadata.background ?? null,
  };
}

/**
 * Merges a patch into one clip's `metadata`, leaving every other field — crucially
 * `effects` (the Chroma Key effect) — byte-identical. Written straight to the store
 * rather than through an action because there is no `clip/setMetadata` action;
 * `GreenScreenSection` sets store state directly in the same way.
 */
export function updateClipMetadata(
  clipId: string,
  patch: Partial<ComponentClipMetadata>,
): void {
  useProjectStore.setState((state) => {
    let touched = false;
    const tracks = state.project.timeline.tracks.map((track) => {
      if (!track.clips.some((clip) => clip.id === clipId)) return track;
      return {
        ...track,
        clips: track.clips.map((clip) => {
          if (clip.id !== clipId) return clip;
          touched = true;
          // Spread the clip: effects, transform, trim points and all else carry over.
          return { ...clip, metadata: { ...(clip.metadata ?? {}), ...patch } };
        }),
      };
    });

    if (!touched) return state;
    return {
      project: {
        ...state.project,
        timeline: { ...state.project.timeline, tracks },
        modifiedAt: Date.now(),
      },
    };
  });
}

/**
 * Stamps component metadata onto any clip that references registered media and does not
 * carry it yet. Idempotent, so it is safe to run on every store change.
 */
export function stampClips(): void {
  const registry = readPending();
  if (Object.keys(registry).length === 0) return;

  const state = useProjectStore.getState();
  const pendingStamps: Array<{ clipId: string; info: Omit<ComponentClipMetadata, "source"> }> = [];

  for (const track of state.project.timeline.tracks) {
    for (const clip of track.clips) {
      const info = registry[clip.mediaId];
      if (!info) continue;
      if (getComponentMetadata(clip)) continue;
      pendingStamps.push({ clipId: clip.id, info });
    }
  }

  for (const { clipId, info } of pendingStamps) {
    updateClipMetadata(clipId, { source: COMPONENT_LIBRARY_SOURCE, ...info });
  }
}

let subscribed = false;

/** Idempotent; called when the Component Library panel first mounts. */
export function initComponentLibraryTracking(): void {
  if (subscribed) return;
  subscribed = true;
  void refreshRegistry();
  stampClips();
  useProjectStore.subscribe((state, previous) => {
    if (state.project.timeline.tracks === previous.project.timeline.tracks) return;
    stampClips();
  });
}
