import type { Clip } from "@openreel/core";

import { useProjectStore } from "../stores/project-store";

/**
 * Bookkeeping for clips generated by the Component Library panel.
 *
 * The panel imports a rendered file into the media library, but the *clip* only exists
 * once the user drops that media on a track — so the component's identity is recorded
 * here against the media id, and stamped onto `clip.metadata` as soon as a clip appears.
 *
 * `Clip.metadata` is typed `ClipMetadata` with an open index signature
 * (`packages/core/src/types/timeline.ts:82`), so this needs no core schema change and
 * survives OpenReel's JSON export/import untouched.
 */

export const COMPONENT_LIBRARY_SOURCE = "component-library";

export interface ComponentClipMetadata {
  source: typeof COMPONENT_LIBRARY_SOURCE;
  componentId: string;
  props: Record<string, unknown>;
  /** The render-service file this clip's media came from, e.g. "7.webm". */
  renderedFileId: string;
  /** Chroma backdrop the file was rendered on, so a re-render reproduces it exactly. */
  background: string | null;
}

type PendingRegistry = Record<string, Omit<ComponentClipMetadata, "source">>;

const STORAGE_KEY = "openreel-component-library-media";

/**
 * mediaId -> component info, for media that has been generated but not yet placed on a
 * track. Mirrored into localStorage so a reload before placement does not lose it.
 */
function readPending(): PendingRegistry {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? (JSON.parse(raw) as PendingRegistry) : {};
  } catch {
    return {};
  }
}

function writePending(registry: PendingRegistry): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(registry));
  } catch {
    // Non-fatal: metadata stamping just falls back to this session's memory.
  }
}

export function registerGeneratedMedia(
  mediaId: string,
  info: Omit<ComponentClipMetadata, "source">,
): void {
  const registry = readPending();
  registry[mediaId] = info;
  writePending(registry);
  stampClips();
}

export function getComponentMetadata(clip: Clip | undefined): ComponentClipMetadata | null {
  const metadata = clip?.metadata as Partial<ComponentClipMetadata> | undefined;
  if (!metadata || metadata.source !== COMPONENT_LIBRARY_SOURCE) return null;
  if (!metadata.componentId) return null;
  return {
    source: COMPONENT_LIBRARY_SOURCE,
    componentId: metadata.componentId,
    props: (metadata.props ?? {}) as Record<string, unknown>,
    renderedFileId: metadata.renderedFileId ?? "",
    background: metadata.background ?? null,
  };
}

/**
 * Merges a patch into one clip's `metadata`, leaving every other field — crucially
 * `effects` (the Chroma Key effect) — byte-identical. Written straight to the store
 * rather than through an action because there is no `clip/setMetadata` action;
 * `GreenScreenSection` sets store state directly in the same way.
 */
export function updateClipMetadata(
  clipId: string,
  patch: Partial<ComponentClipMetadata>,
): void {
  useProjectStore.setState((state) => {
    let touched = false;
    const tracks = state.project.timeline.tracks.map((track) => {
      if (!track.clips.some((clip) => clip.id === clipId)) return track;
      return {
        ...track,
        clips: track.clips.map((clip) => {
          if (clip.id !== clipId) return clip;
          touched = true;
          // Spread the clip: effects, transform, trim points and all else carry over.
          return { ...clip, metadata: { ...(clip.metadata ?? {}), ...patch } };
        }),
      };
    });

    if (!touched) return state;
    return {
      project: {
        ...state.project,
        timeline: { ...state.project.timeline, tracks },
        modifiedAt: Date.now(),
      },
    };
  });
}

/**
 * Stamps component metadata onto any clip that references registered media and does not
 * carry it yet. Idempotent, so it is safe to run on every store change.
 */
export function stampClips(): void {
  const registry = readPending();
  if (Object.keys(registry).length === 0) return;

  const state = useProjectStore.getState();
  const pendingStamps: Array<{ clipId: string; info: Omit<ComponentClipMetadata, "source"> }> = [];

  for (const track of state.project.timeline.tracks) {
    for (const clip of track.clips) {
      const info = registry[clip.mediaId];
      if (!info) continue;
      if (getComponentMetadata(clip)) continue;
      pendingStamps.push({ clipId: clip.id, info });
    }
  }

  for (const { clipId, info } of pendingStamps) {
    updateClipMetadata(clipId, { source: COMPONENT_LIBRARY_SOURCE, ...info });
  }
}

let subscribed = false;

/** Idempotent; called when the Component Library panel first mounts. */
export function initComponentLibraryTracking(): void {
  if (subscribed) return;
  subscribed = true;
  stampClips();
  useProjectStore.subscribe((state, previous) => {
    if (state.project.timeline.tracks === previous.project.timeline.tracks) return;
    stampClips();
  });
}
